add --mirrorlist option

diff --git a/apt-cyg b/apt-cyg
--- a/apt-cyg
+++ b/apt-cyg
@@ -3,19 +3,19 @@
 # apt-cyg: install tool for cygwin similar to debian apt-get
 
 # The MIT License (MIT)
-# 
+#
 # Copyright (c) 2013 Trans-code Design
-# 
+#
 # Permission is hereby granted, free of charge, to any person obtaining a copy
 # of this software and associated documentation files (the "Software"), to deal
 # in the Software without restriction, including without limitation the rights
 # to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 # copies of the Software, and to permit persons to whom the Software is
 # furnished to do so, subject to the following conditions:
-# 
+#
 # The above copyright notice and this permission notice shall be included in
 # all copies or substantial portions of the Software.
-# 
+#
 # THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 # IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 # FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
@@ -23,7 +23,7 @@
 # LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 # OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 # THE SOFTWARE.
-# 
+#
 
 # this script requires some packages
 
@@ -51,6 +51,7 @@ function usage()
   echo "  \"apt-cyg packageof <commands or files>\" to locate parent packages"
   echo "Options:"
   echo "  --mirror, -m <url> : set mirror"
+  echo "  --mirrorlist, -l <file> : set mirrorlist file (default to /etc/setup/mirrorlist)"
   echo "  --cache, -c <dir>  : set cache"
   echo "  --file, -f <file>  : read package names from file"
   echo "  --noupdate, -u     : don't update setup.ini from mirror"
@@ -71,25 +72,37 @@ function version()
 
 function findworkspace()
 {
-  # default working directory and mirror
-  
-  mirror=ftp://mirror.mcs.anl.gov/pub/cygwin
+  # default working directory and set mirrors
+
+  if test -z "$mirrorlist"
+  then
+      echo "mirrorlist not set." # won't happen
+      exit 1
+  fi
+  echo Mirrorlist is $mirrorlist
+
+  mirrors=ftp://mirror.mcs.anl.gov/pub/cygwin
   cache=/setup
-  
+
   # work wherever setup worked last, if possible
-  
+
   if test -e /etc/setup/last-cache
   then
     tmp="`head -1 /etc/setup/last-cache`"
     cache="`cygpath -au "$tmp"`"
   fi
-  
-  if test -e /etc/setup/last-mirror
+
+  if test -e "$mirrorlist"
   then
-    mirror="`head -1 /etc/setup/last-mirror`"
+    mirrors="`grep -v "^#" <$mirrorlist`"
   fi
+}
+
+function setworkspace(){
+  # set workspace
+  mirror=$1
   mirrordir="`echo "$mirror" | sed -e "s/:/%3a/g" -e "s:/:%2f:g"`"
-  
+
   echo Working directory is $cache
   echo Mirror is $mirror
   mkdir -p "$cache/$mirrordir"
@@ -97,7 +110,7 @@ function findworkspace()
 }
 
 
-function getsetup() 
+function getsetup()
 {
   if test "$noscripts" == "0" -a "$noupdate" == "0"
   then
@@ -143,6 +156,9 @@ command=""
 filepackages=""
 packages=""
 
+mirrorlist="/etc/setup/mirrorlist"
+mirrors=
+
 while test $# -gt 0
 do
   case "$1" in
@@ -150,6 +166,17 @@ do
     --mirror|-m)
       echo "$2" > /etc/setup/last-mirror
       shift ; shift
+    ;;
+
+    --mirrorlist|-l)
+      if ! test "-$2-" = "--"
+      then
+        mirrorlist="$2"
+        shift
+      else
+        echo 1>&2 No file name provided, ignoring $1
+      fi
+      shift
     ;;
 
     --cache|-c)
@@ -214,7 +241,7 @@ if test $dofile = 1
 then
   if test -f "$file"
   then
-    filepackages="$filepackages `cat "$file" | awk '{printf "%s ", $0}'`"
+    filepackages="$filepackages $(cat "$file" | awk '{printf "%s ", $0}')"
   else
     echo File $file not found, skipping
   fi
@@ -227,7 +254,11 @@ case "$command" in
   update)
 
     findworkspace
-    getsetup
+    for mirror in $mirrors
+    do
+        setworkspace $mirror
+        getsetup
+    done
 
   ;;
 
@@ -244,17 +275,21 @@ case "$command" in
 
     checkpackages
     findworkspace
-    getsetup
 
-    for pkg in $packages
+    for mirror in $mirrors
     do
-      echo ""
-      echo Searching for installed packages matching $pkg:
-      awk '/[^ ]+ [^ ]+ 0/ {if ($1 ~ query) print $1}' query="$pkg" /etc/setup/installed.db
-      echo ""
-      echo Searching for installable packages matching $pkg:
-      cat setup.ini | awk -v query="$pkg" \
-        'BEGIN{RS="\n\n@ "; FS="\n"; ORS="\n"} {if ($1 ~ query) {print $1}}'
+        setworkspace $mirror
+        getsetup
+        for pkg in $packages
+        do
+            echo ""
+            echo Searching for installed packages matching $pkg:
+            awk '/[^ ]+ [^ ]+ 0/ {if ($1 ~ query) print $1}' query="$pkg" /etc/setup/installed.db
+            echo ""
+            echo Searching for installable packages matching $pkg:
+            cat setup.ini | awk -v query="$pkg" \
+                'BEGIN{RS="\n\n@ "; FS="\n"; ORS="\n"} {if ($1 ~ query) {print $1}}'
+        done
     done
 
   ;;
@@ -264,12 +299,16 @@ case "$command" in
 
     checkpackages
     findworkspace
-    getsetup
-    for pkg in $packages
+    for mirror in $mirrors
     do
-      echo ""
-      cat setup.ini | awk -v query="$pkg" \
-        'BEGIN{RS="\n\n@ "; FS="\n"; ORS="\n"} {if ($1 ~ query) {print $0 "\n"}}'
+        setworkspace $mirror
+        getsetup
+        for pkg in $packages
+        do
+            echo ""
+            cat setup.ini | awk -v query="$pkg" \
+                'BEGIN{RS="\n\n@ "; FS="\n"; ORS="\n"} {if ($1 ~ query) {print $0 "\n"}}'
+        done
     done
 
   ;;
@@ -303,120 +342,125 @@ case "$command" in
 
     checkpackages
     findworkspace
-    getsetup
-
-    for pkg in $packages
+    for mirror in $mirrors
     do
+        setworkspace $mirror
+        getsetup
 
-    already=`grep -c "^$pkg " /etc/setup/installed.db`
-    if test $already -ge 1
-    then
-      echo Package $pkg is already installed, skipping
-      continue
-    fi
-    echo ""
-    echo Installing $pkg
+        for pkg in $packages
+        do
 
-    # look for package and save desc file
+            already=`grep -c "^$pkg " /etc/setup/installed.db`
+            if test $already -ge 1
+            then
+                echo Package $pkg is already installed, skipping
+                continue
+            fi
+            echo ""
+            echo Installing $pkg
 
-    mkdir -p "release/$pkg"
-    cat setup.ini | awk > "release/$pkg/desc" -v package="$pkg" \
-      'BEGIN{RS="\n\n@ "; FS="\n"} {if ($1 == package) {desc = $0; px++}} \
-       END {if (px == 1 && desc != "") print desc; else print "Package not found"}' 
-    
-    desc=`cat "release/$pkg/desc"`
-    if test "-$desc-" = "-Package not found-"
-    then
-      echo Package $pkg not found or ambiguous name, exiting
-      rm -r "release/$pkg"
-      exit 1
-    fi
-    echo Found package $pkg
+            # look for package and save desc file
 
-    # download and unpack the bz2 file
+            mkdir -p "release/$pkg"
+            cat setup.ini | awk > "release/$pkg/desc" -v package="$pkg" \
+                'BEGIN{RS="\n\n@ "; FS="\n"} {if ($1 == package) {desc = $0; px++}} \
+       END {if (px == 1 && desc != "") print desc; else print "Package not found"}'
 
-    # pick the latest version, which comes first
-    install=`cat "release/$pkg/desc" | awk '/^install: / { print $2; exit }'` 
+            desc=`cat "release/$pkg/desc"`
+            if test "-$desc-" = "-Package not found-"
+            then
+                echo Package $pkg not found or ambiguous name, exiting
+                rm -r "release/$pkg"
+                exit 1
+            fi
+            echo Found package $pkg
 
-    if test "-$install-" = "--"
-    then
-      echo "Could not find \"install\" in package description: obsolete package?"
-      exit 1
-    fi
+            # download and unpack the bz2 file
 
-    file=`basename $install`
-    cd "release/$pkg"
-    wget -nc $mirror/$install
-    
-    # check the md5
-    digest=`cat "desc" | awk '/^install: / { print $4; exit }'` 
-    digactual=`md5sum $file | awk '{print $1}'`
-    if ! test $digest = $digactual
-    then
-      echo MD5 sum did not match, exiting
-      exit 1
-    fi
-    
-    echo "Unpacking..."
-    cat $file | bunzip2 | tar > "/etc/setup/$pkg.lst" xvf - -C /
-    gzip -f "/etc/setup/$pkg.lst"
-    cd ../..
-    
-    
-    # update the package database
-    
-    cat /etc/setup/installed.db | awk > /tmp/awk.$$ -v pkg="$pkg" -v bz=$file \
-      '{if (ins != 1 && pkg < $1) {print pkg " " bz " 0"; ins=1}; print $0} \
+            # pick the latest version, which comes first
+            install=`cat "release/$pkg/desc" | awk '/^install: / { print $2; exit }'`
+
+            if test "-$install-" = "--"
+            then
+                echo "Could not find \"install\" in package description: obsolete package?"
+                exit 1
+            fi
+
+            file=`basename $install`
+            cd "release/$pkg"
+            wget -nc $mirror/$install
+
+            # check the md5
+            digest=`cat "desc" | awk '/^install: / { print $4; exit }'`
+            digactual=`md5sum $file | awk '{print $1}'`
+            if ! test $digest = $digactual
+            then
+                echo MD5 sum did not match, exiting
+                exit 1
+            fi
+
+            echo "Unpacking..."
+            cat $file | bunzip2 | tar > "/etc/setup/$pkg.lst" xvf - -C /
+            gzip -f "/etc/setup/$pkg.lst"
+            cd ../..
+
+
+            # update the package database
+
+            cat /etc/setup/installed.db | awk > /tmp/awk.$$ -v pkg="$pkg" -v bz=$file \
+                '{if (ins != 1 && pkg < $1) {print pkg " " bz " 0"; ins=1}; print $0} \
        END{if (ins != 1) print pkg " " bz " 0"}'
-    mv /etc/setup/installed.db /etc/setup/installed.db-save
-    mv /tmp/awk.$$ /etc/setup/installed.db
-    
-    
-    # recursively install required packages
-    
-    echo > /tmp/awk.$$ '/^requires: / {s=gensub("(requires: )?([^ ]+) ?", "\\2 ", "g", $0); print s}'
-    requires=`cat "release/$pkg/desc" | awk -f /tmp/awk.$$`
-    
-    warn=0
-    if ! test "-$requires-" = "--"
-    then
-      echo Package $pkg requires the following packages, installing:
-      echo $requires
-      for package in $requires
-      do
-        already=`grep -c "^$package " /etc/setup/installed.db`
-        if test $already -ge 1
-        then
-          echo Package $package is already installed, skipping
-          continue
-        fi
-        apt-cyg --noscripts install $package
-        if ! test $? = 0 ; then warn=1; fi
-      done
-    fi
-    if ! test $warn = 0
-    then
-      echo "Warning: some required packages did not install, continuing"
-    fi
-    
-    # run all postinstall scripts
-    
-    pis=`ls /etc/postinstall/*.sh 2>/dev/null | wc -l`
-    if test $pis -gt 0 && ! test $noscripts -eq 1
-    then
-      echo Running postinstall scripts
-      for script in /etc/postinstall/*.sh
-      do
-        $script
-        mv $script $script.done
-      done
-    fi
-    
-    echo Package $pkg installed
+            mv /etc/setup/installed.db /etc/setup/installed.db-save
+            mv /tmp/awk.$$ /etc/setup/installed.db
+
+
+            # recursively install required packages
+
+            echo > /tmp/awk.$$ '/^requires: / {s=gensub("(requires: )?([^ ]+) ?", "\\2 ", "g", $0); print s}'
+            requires=`cat "release/$pkg/desc" | awk -f /tmp/awk.$$`
+
+            warn=0
+            if ! test "-$requires-" = "--"
+            then
+                echo Package $pkg requires the following packages, installing:
+                echo $requires
+                for package in $requires
+                do
+                    already=`grep -c "^$package " /etc/setup/installed.db`
+                    if test $already -ge 1
+                    then
+                        echo Package $package is already installed, skipping
+                        continue
+                    fi
+                    apt-cyg --noscripts install $package
+                    if ! test $? = 0 ; then warn=1; fi
+                done
+            fi
+            if ! test $warn = 0
+            then
+                echo "Warning: some required packages did not install, continuing"
+            fi
+
+            # run all postinstall scripts
+
+            pis=`ls /etc/postinstall/*.sh 2>/dev/null | wc -l`
+            if test $pis -gt 0 && ! test $noscripts -eq 1
+            then
+                echo Running postinstall scripts
+                for script in /etc/postinstall/*.sh
+                do
+                    $script
+                    mv $script $script.done
+                done
+            fi
+
+            echo Package $pkg installed
+
+        done
 
     done
 
-  ;;
+    ;;
 
 
   remove)
@@ -476,4 +520,3 @@ case "$command" in
   ;;
 
 esac
-
